### ISSUE TITLE
AMI cannot be described

### ISSUE THREAD

**Issue by vsurugiu** [aerospike/aws-cloudformation#14]
Trying to run the cloudformation stack with both full vpc and existing vpc yelds the following autoscaling launch configuration error: "AMI cannot be described" 
Looking in the list of public Aerospike ami's the latest one that i could see available is ami-2e6dc55d with version 3.7.1 but no 3.7.2 ami available in EU-WEST-1 region. 
It seems that the 3.7.2 ami has not been made publicly available but the stack reference it.

Thanks

**Comment by vsurugiu** [comment]
the ami that is in the stack and not publicly available is ami-647dc917

**Comment by whyrg** [comment]
Due to a backlog on Amazon's side, 3.7.2 has not yet been published on the marketplace. You may use the commit prior to spin up a 3.7.1 cluster. I will update this thread once I have confirmation from Amazon that 3.7.2 has been made available.

**Comment by whyrg** [comment]
3.7.2 is now available on the marketplace.
