### ISSUE TITLE
Existing VPC template fails if a default VPC doesn't exist

### ISSUE THREAD

**Issue by medavisjr** [aerospike/aws-cloudformation#24]
If you run the Existing VPC CloudFormation template in an account that doesn't have a default VPC (e.g. the admin is good and removed the default VPC), the `PsuedoRandom` resource fails to create with the following error:

```
No default VPC for this user (Service: AmazonEC2; Status Code: 400; Error Code: VPCIdNotSpecified; Request ID: 1a4dcb4e-26a0-47b9-81da-8a7a711c217d; Proxy: null)
```

This is because the `AWS::EC2::SecurityGroup` CF resource uses the default VPC in the region if no `VpcId` parameter value is provided to it. If no default VPC exists, it bombs out.

The correct way to do this would be to specify the `VpcId` property in the `PsuedoRandom` resource and assign it the value of the `VPCID` stack parameter.

Also, you misspelled "pseudo" in the `PsuedoRandom` resource name!

This whole thing of creating a resource to generate a UID is not a good approach, IMO. If you want a UID for labelling/naming resources in the stack, just use [AWS::StackId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackid) and grab the ID from the ARN it outputs using a split:

```
Value: !Select [2, !Split ['/', !Ref AWS::StackId]]
```

**Comment by sourabh3b** [comment]
Thanks for the issue. This repo is not longer maintained, will reply in other repo, closing this issue here and will take it on other repo where you linked this.
