### ISSUE TITLE
AMI ids outdated

### ISSUE THREAD

**Issue by aps-sids** [aerospike/aws-cloudformation#4]
Hardcoded ami-ids are for an older version of Aerospike and need to be updated.

Also, is there a way to update the config file by means of this cloudformation script?

**Comment by mtendjou** [comment]
Thanks for bringing this up. The cloudformation script was just updated. And it does update the config file. You should be able to figure this out from the script itself, let us know otherwise.

**Comment by aps-sids** [comment]
Ah, I see. Thanks. I was looking for a simple way to update `namespace` config options from this script.
